spring.data.mongodb.uri=mongodb+srv://joel-navarro:Sw13yo3L5PiQTJB0@cluster0.mmzmrs9.mongodb.net/franchise_management?retryWrites=true&w=majority
spring.application.name=franchise-service
server.port=8080